services:
 nginx:
  build: requirements/nginx/.
  container_name: nginx
  depends_on:
   - wordpress
   - mariadb
  ports:
   - "443:443"
  restart: always
  volumes:
   - wp-volume:/var/www/html
  networks:
   - inception
 wordpress:
  build: requirements/wordpress/.
  container_name: wp-php
  restart: always
  volumes:
   - wp-volume:/var/www/html
  networks:
   - inception
  depends_on:
   - mariadb
  env_file:
  - .env
 mariadb:
  build: requirements/mariadb/.
  container_name: mariadb
  restart: always
  volumes:
  - db-volume:/var/lib/mysql
  networks:
  - inception
  env_file:
  - .env

volumes:
  wp-volume:
    driver_opts:
      o: bind
      type: none
      device: /Users/machi/data/wordpress
  db-volume:
    driver_opts:
      o: bind
      type: none
      device: /Users/machi/data/mariadb

networks:
 inception:
  driver: bridge